name: GirlsClubiOS
options:
  bundleIdPrefix: com.girlsclub
  deploymentTarget:
    iOS: 15.0
configs:
  Debug: debug
  Release: release
settings:
  base:
    SWIFT_VERSION: 5.9
targets:
  GirlsClubiOS:
    type: application
    platform: iOS
    sources:
      - path: GirlsClubiOS
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.girlsclub.ios
        INFOPLIST_FILE: GirlsClubiOS/Supporting/Info.plist
    configFiles:
      Debug: Config/Secrets.xcconfig
      Release: Config/Secrets.xcconfig
    dependencies:
      - package: Supabase
      - package: Stripe
packages:
  Supabase:
    url: https://github.com/supabase-community/supabase-swift
    from: 2.0.0
  Stripe:
    url: https://github.com/stripe/stripe-ios
    from: 24.0.0
